name: todo
services:
  database:
    image: "postgres:17"
    container_name: todo-database
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres